trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguation)
  displayName: 'dotnet build $(buildConfiguration)'